include: package:lints/recommended.yaml

analyzer:
  errors:
    # Ignore ces avertissements et erreurs dans tout le projet
    non_constant_identifier_names : ignore
    constant_identifier_names : ignore
    file_names: ignore
