name: fralacticus_modificateur_images_bf_log2
repository: https://github.com/Fralacticus/fralacticus_modificateur_images_bf_log2

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
